name: 🧩 Perform GitHub Release

on:
  workflow_call:
    inputs:
      force:
        description: Force the release (overwrite existing tag)
        type: boolean
        required: false
        default: true

jobs:
  release:
    name: Release 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Fetch data from manifest.yaml
        id: manifest
        uses: albr21/gha-manifest@1.0.0
        with:
          manifest: manifest.yaml

      - name: Create GitHub Release
        uses: albr21/gha-create-github-release@1.0.0
        with:
          sha: ${{ github.sha }}
          tag: ${{ steps.manifest.outputs.release-version }}
          title: ${{ steps.manifest.outputs.release-title }}
          body: ${{ steps.manifest.outputs.release-body }}
          force: ${{ inputs.force }}
