name: 🧩 Python Quality

on:
  workflow_call:
    inputs:
      docker-image:
        description: Docker image to use. Should be a Python image.
        type: string
        default: ghcr.io/albr21/python-3.13:1.0.0-alpine
      path:
        description: Path to the Python code to analyze
        type: string
        default: src
      cov-threshold:
        description: Minimum test coverage percentage to pass the build
        type: string
        default: '80'
      lint-threshold:
        description: Minimum pylint score considered acceptable (does NOT fail the build)
        type: string
        default: '7.0'
      pylintrc:
        description: Path to a custom pylint configuration file (pylintrc)
        type: string
        default: ''
      requirements:
        description: Path to the requirements file
        type: string
        default: requirements.txt
      requirements-dev:
        description: Path to the dev requirements file
        type: string
        default: requirements-dev.txt

jobs:
  test:
    name: Tests & Coverage
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Python environment
        uses: albr21/gha-py-venv@1.0.0
        with:
          requirements: ${{ inputs.requirements }}
          requirements-dev: ${{ inputs.requirements-dev }}

      - name: Run tests with coverage
        uses: albr21/gha-pytest@1.0.0
        with:
          path: ${{ inputs.path }}
          cov-threshold: ${{ inputs.cov-threshold }}

  lint:
    name: Linting
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Python environment
        uses: albr21/gha-py-venv@1.0.0
        with:
          requirements: ${{ inputs.requirements }}
          requirements-dev: ${{ inputs.requirements-dev }}

      - name: Run pylint
        uses: albr21/gha-pylint@1.0.0
        with:
          path: ${{ inputs.path }}
          lint-threshold: ${{ inputs.lint-threshold }}
          pylintrc: ${{ inputs.pylintrc }}
